version: '3' # specify docker-compose version

services:
  frontend:
    container_name: kt-frontend
    build: ./webapp/key-trader
    ports:
      - "4200:4200"
      - "9876:9876"
    environment:
      - "ENV=${ENV}"
    volumes:
      - /client/node_modules # ignore host node_modules
      - /webapp/key-trader/dist # ignore host prod build files
      - ./webapp/key-trader:/client # used for live reloading
      - ./dockerShare/dist:/client/dist/key-trader # used for making prod build files available to nginx

  backend:
    container_name: kt-backend
    restart: always
    build: ./webapp/backend
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - database
    volumes:
      - /usr/src/app/node_modules # ignore host node_modules
      - ./webapp/backend:/usr/src/app # used for live reloading

  database:
    container_name: kt-database
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "keytrader"
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: "1234"
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d # map initialization scripts
      - ./dockerShare/mysql_data:/var/lib/mysql # map db data

  discordbot:
    container_name: kt-discordbot
    build: ./discordBot
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - /usr/src/app/node_modules # ignore host node_modules

  webserver:
    container_name: kt-webserver
    restart: always
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./dockerShare/dist:/usr/share/nginx/html:ro
